### ISSUE TITLE
Override browserSync config

### ISSUE THREAD

**Issue by karneaud** [jsqrt/bun-bundler#1]
Any particular reason you are setting the [configurations for browsersync in the way you do?](https://github.com/jsqrt/bun-bundler/blob/0ba9e89c44facaa5c7c779d0539626f3cb72830b/modules/server.js#L58) I have my own configuration that I would like to use as the ui ports seem to have some side effects when I use the defaults

```
jsDist: `${dist}/js/`,
		onStart: () => {
			server.startServer({
				open: false,
                host: '0.0.0.0',
                codeSync: true,
				debug: debugMode,
				port: 3000,
				root: dist,
                ui: {
                    port: 3001,
                    weinre: {
                        port: 3002
                    }
                }
			});
		},
		```

**Comment by jsqrt** [comment]
> Any particular reason you are setting the [configurations for browsersync in the way you do?](https://github.com/jsqrt/bun-bundler/blob/0ba9e89c44facaa5c7c779d0539626f3cb72830b/modules/server.js#L58) I have my own configuration that I would like to use as the ui ports seem to have some side effects when I use the defaults
> 
> ```
> jsDist: `${dist}/js/`,
> 		onStart: () => {
> 			server.startServer({
> 				open: false,
>                 host: '0.0.0.0',
>                 codeSync: true,
> 				debug: debugMode,
> 				port: 3000,
> 				root: dist,
>                 ui: {
>                     port: 3001,
>                     weinre: {
>                         port: 3002
>                     }
>                 }
> 			});
> 		},
> 		```
> ```

Thanks for pointing that out. You`re absolutely right, need to add that functionality 👍.
I'm currently working through the documentation and usage examples to ensure a smoother dev experience.
However, this is something I’m doing in my free time :)
Obviously, you can help with it, and I'd really appreciate it.

**Comment by jsqrt** [comment]
fixed! 
try this: 
```
server.startServer({
	open: true, // if needed
	debug: debugMode,
	root: dist,
	overrides: {
		host: '0.0.0.0',
		codeSync: true,
		debug: debugMode,
		port: 3000,
		root: dist,
		ui: {
			port: 3001,
			weinre: {
				port: 3002,
			},
		},
	},
});
```
