### ISSUE TITLE
Sass does can't import stylesheet

### ISSUE THREAD

**Issue by karneaud** [jsqrt/bun-bundler#4]
I'm not sure if its your package or my project dependency package but when trying to import node_modules/_sass-library_ I get the error

> Can't find/ import stylesheet, file does not exist

Usually 

`@import ~bootstrap/css/file` or `@use bootstrap/css/file` would work but I  had to reference it `@forward .../../node_modules/....` which lead to more internal referencing issues.

I  had to 

```
this.config.jsFiles = exec(js);
this.config.staticFolders = exec(staticFolders);
this.config.sassLoadPaths = exec(sassLoadPaths); // add a configurations to allow search in folders other than source
	
```

and also

```
	await this.compile({
				filePaths: this.config.sassFiles,
				type: 'CSS',
				newFileExt: '.css',
				dist: this.config.cssDist,
				renderFn: (filePath) => sass.compile(filePath, { style: 'compressed',  loadPaths: this.config.sassLoadPaths  })?.css,
```

and it worked!

Maybe it could recognize *.sassrc* files in the project thus we can loadPaths from there ??

**Comment by jsqrt** [comment]
@karneaud 

Added new parameters, I hope they will work for you. 

Also it might be useful if you need to pass custom environment variables to the pug template.

```
bundler.build({
	sassConfigOverrides: {
		filePaths: ['../node_modules/'],
	},
	pugConfigOverrides: {},
	jsConfigOverrides: {},

	...other options
});

```

**Comment by karneaud** [comment]
@jsqrt Good looking out! the pug configs would be useful

**Comment by karneaud** [comment]
Question here.  Usually sass framework would look for the .sassrc file. I assume because we are manually triggering it that this doesn't happen. Is there anyway we can have sass scan for config files as oppose to having to input configs manually? Not that I'm complaining but for people who migrate from parceljs it might prove useful. How does sass detect a .sassrc file?

**Comment by jsqrt** [comment]
Ok, I think we can do that :)

Get the contents of .sassrc via “fs.readFileSync”. 

Then set as default configuration.

**Comment by jsqrt** [comment]
@karneaud Fixed, please check 😊
